# Site settings
title: kiliansinger/codetricks
repository: kiliansinger/codetricks
description: >-
  Programming tricks for STEM wizards.

markdown: GFM 
plugins:
- jekyll-gfm-admonitions
- jekyll-optional-front-matter

url: https://kiliansinger.github.io
baseurl: /kiliansinger #the subpath of your site, e.g. /blog

exclude: 
  - "**/*.ts" # Exclude source code files!
  - "**/*.js"
  - "*.ts" # Also those in the root directory!
  - "*.js"
  - "*.json" # Don't forget about assets!
  - node_modules/ # And large vendored directories
  # And these ignore all the artifacts the build produces:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# for [!WARNING] to work https://github.com/Helveg/jekyll-gfm-admonitions